spring:
  application:
    name: parcel-cost-calculator
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com:
      fabiankevin: INFO


voucher:
  baseUrl: mynt-exam.mocklab.io
  apikey: apikey